version: '3.8'
services:
  db: # PostreSQL
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messenger
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  adminer: # DB control UI
    image: adminer
    ports:
      - "8080:8080"
volumes:
  db-data:
